title: RubyOS website
description: Discover RubyOS based on a stripped version of Windows 10 LTSC 2021. A debloated, optimized, and private OS designed to revive older hardware and maximize performance.